// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Whataline.Infrastructure.Data;

#nullable disable

namespace Whataline.Infrastructure.Migrations;

[DbContext(typeof(WhatalineDbContext))]
partial class WhatalineDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("Whataline.Core.Entities.AdminUser", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.HasIndex("Username").IsUnique();
            b.ToTable("AdminUsers");
        });

        modelBuilder.Entity("Whataline.Core.Entities.WritingProject", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<bool>("Featured").HasColumnType("bit");
            b.Property<string>("Format").HasColumnType("nvarchar(max)");
            b.Property<string>("Genre").HasColumnType("nvarchar(max)");
            b.Property<string>("Logline").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("PosterUrl").HasColumnType("nvarchar(max)");
            b.Property<string>("ScriptUrl").HasColumnType("nvarchar(max)");
            b.Property<int>("SortOrder").HasColumnType("int");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("draft").HasColumnType("nvarchar(20)");
            b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.ToTable("WritingProjects");
        });

        modelBuilder.Entity("Whataline.Core.Entities.FilmProject", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<bool>("Featured").HasColumnType("bit");
            b.Property<string>("FilmUrl").HasColumnType("nvarchar(max)");
            b.Property<string>("Format").HasColumnType("nvarchar(max)");
            b.Property<string>("Genre").HasColumnType("nvarchar(max)");
            b.Property<string>("Logline").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("PosterUrl").HasColumnType("nvarchar(max)");
            b.Property<int>("SortOrder").HasColumnType("int");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("draft").HasColumnType("nvarchar(20)");
            b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
            b.Property<string>("TrailerUrl").HasColumnType("nvarchar(max)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.Property<int?>("Year").HasColumnType("int");
            b.HasKey("Id");
            b.ToTable("FilmProjects");
        });

        modelBuilder.Entity("Whataline.Core.Entities.Award", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            b.Property<string>("Category").HasColumnType("nvarchar(max)");
            b.Property<int?>("FilmProjectId").HasColumnType("int");
            b.Property<string>("Name").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
            b.Property<int?>("WritingProjectId").HasColumnType("int");
            b.Property<int?>("Year").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("FilmProjectId");
            b.HasIndex("WritingProjectId");
            b.ToTable("Awards");
        });

        modelBuilder.Entity("Whataline.Core.Entities.Award", b =>
        {
            b.HasOne("Whataline.Core.Entities.FilmProject", "FilmProject")
                .WithMany("Awards")
                .HasForeignKey("FilmProjectId")
                .OnDelete(DeleteBehavior.Cascade);
            b.HasOne("Whataline.Core.Entities.WritingProject", "WritingProject")
                .WithMany("Awards")
                .HasForeignKey("WritingProjectId")
                .OnDelete(DeleteBehavior.Cascade);
        });
#pragma warning restore 612, 618
    }
}
